# Generated by Django 4.2.16 on 2024-10-14 20:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name_plural": "3 . Course"},
        ),
        migrations.AlterModelOptions(
            name="coursecategory",
            options={"verbose_name_plural": "2 . Course Categories"},
        ),
        migrations.AlterModelOptions(
            name="lecturer",
            options={"verbose_name_plural": "1 . Lecturer"},
        ),
        migrations.AlterModelOptions(
            name="student",
            options={"verbose_name_plural": "4 . Student"},
        ),
    ]
